### ISSUE TITLE
RPC Button

### ISSUE THREAD

**Issue by mayberks** [alexmercerind/dart_discord_rpc#1]
You should also add the RPC Button event that Discord supports. It would be a really nice feature.

**Comment by alexmercerind** [comment]
@mayberks @edeuss @Gorgosus

I implemented buttons few days back in the [`harmonoid`](https://github.com/alexmercerind/dart_discord_rpc/tree/harmonoid) branch. You can use this plugin from `git` for now.

Add in your `pubspec.yaml`.

```yaml
dependencies:
  dart_discord_rpc:
    git:
      url: https://github.com/alexmercerind/dart_discord_rpc.git
      ref: harmonoid
```

**Example Code:**

Pass `button1Label` & `button1Url` to the constructor of `DiscordPresence`. Only two buttons are allowed by Discord.

```dart
final rpc = DiscordRPC(applicationId: '877853131025809438');
rpc.start(autoRegister: true);
rpc.updatePresence(
  DiscordPresence(
    state: 'text1',
    details: 'text2',
    startTimeStamp: DateTime.now().millisecondsSinceEpoch,
    largeImageKey: 'large_image',
    largeImageText: 'label1',
    smallImageKey: 'small_image',
    smallImageText: 'label2',
    button1Label: 'GitHub',
    button1Url: 'https://github.com',
    button2Label: 'Google',
    button2Url: 'https://www.google.com',
  ),
);
```

So far, implementation is very stable & being used in production in my hobby application [Harmonoid](https://harmonoid.com). I just didn't get time to update the pub.dev implementation.

<img height="auto" width="600" src="https://alexmercerind.github.io/harmonoid-website/assets/images/discord-86250e849259f16ce56a75a533035889.webp">

<hr>

And specifically @Gorgosus, please avoid spamming people's repositories/mails. 
Please don't consider everyone's time to be free, everyone is busy with job, education or personal-life.
None of this is "for granted".
As they say:
> Don't complain about the things you're not willing to change.

It's an open source project, everyone is free to add their features & contribute back. I owe no-one quite simply.
What are your expectations, when you haven't even starred the repository.

**Comment by mayberks** [comment]
Thanks for adding the feature. It's great to have this feature. Good job!
