### ISSUE TITLE
Field '_dynamicLibrary@21084338' has not been initialized.

### ISSUE THREAD

**Issue by AndreZila01** [alexmercerind/dart_discord_rpc#23]
Hey, 

i try run in my project [your code](https://github.com/alexmercerind/dart_discord_rpc/tree/master/example) and change application id, but the project return this error:

![image](https://user-images.githubusercontent.com/56931353/186924015-38fb1326-4069-45e7-a81c-a20e2049140d.png)

Can explain how i can solve this?

**Comment by alexmercerind** [comment]
- Mobile not supported.
- Add `await` before `DiscordRPC.initialize`.
